IMPALA-8177: Log DDL failures in coordinator logs
If a DDL fails for some reason, it helps to log the failure message in
the coordinator logs so that we can differentiate between failed and
successful DDL queries.

For ex:

[0d66cd6004b4:21000] default> drop database foo;
Query: drop database foo
ERROR: ImpalaRuntimeException: Error making 'dropDatabase' RPC to Hive Metastore:
CAUSED BY: NoSuchObjectException: foo
----- coordinator logs -------
I0208 12:13:26.251695 25474 Frontend.java:1242] 704e86fff482c0b5:f0501f9400000000] Analyzing query: drop database foo
I0208 12:13:26.253773 25474 Frontend.java:1282] 704e86fff482c0b5:f0501f9400000000] Analysis finished.
I0208 12:13:26.419946 25474 client-request-state.cc:176] 704e86fff482c0b5:f0501f9400000000] ImpalaRuntimeException: Error making 'dropDatabase' RPC to Hive Metastore:
CAUSED BY: NoSuchObjectException: foo
I0208 12:13:26.419992 25474 impala-server.cc:1142] 704e86fff482c0b5:f0501f9400000000] UnregisterQuery(): query_id=704e86fff482c0b5:f0501f9400000000
I0208 12:13:26.419997 25474 impala-server.cc:1249] 704e86fff482c0b5:f0501f9400000000] Cancel(): query_id=704e86fff482c0b5:f0501f9400000000
-------------------------------

Testing: Verified manually by running a few DDLs that fail and then inspecting
the coordinator log file.

Change-Id: Ie89291ee27156c701e07cea44ad3ee07ec54ab42
Reviewed-on: http://gerrit.cloudera.org:8080/12414
Reviewed-by: Bharath Vissapragada <bharathv@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>