Remove hwx.public.repo maven repo
The hwx.public.repo (nexus-private.hortonworks.com) contains jars that
conflict with impala.cdh.repo (GBN based s3 bucket). This means that
Impala can build and test with a mix of jars from both. The latest
symptom of this is frontend tests failing with messages like:
java.lang.NoClassDefFoundError: org/apache/hadoop/security/ssl/OpenSSLSocketFactory$SSLChannelMode
This happens because hadoop-aws is on a more recent version than
hadoop-common.

Since Impala builds without the hwx.public.repo, let's remove it.

Change-Id: I6f1cf7efcad522c2df228c8c2b8068bb3002e407
Reviewed-on: http://gerrit.cloudera.org:8080/13403
Reviewed-by: Fredy Wijaya <fwijaya@cloudera.com>
Tested-by: Joe McDonnell <joemcdonnell@cloudera.com>
(cherry picked from commit cb331d0e6048ba6bf68f58f6ea1cb69017e5d12b)

Change-Id: I89c8ece1d0f03e144d0566e1e446b50b7af9f456
Reviewed-on: https://gerrit.sjc.cloudera.com/c/cdh/impala/+/46931
Reviewed-by: Jenkins User <jenkins@cloudera.com>
CDH-Build: Jenkins User <jenkins@cloudera.com>
Tested-by: Jenkins User <jenkins@cloudera.com>
Quasar-L0: quasar-precommit User
Quasar-L0: Jenkins User <jenkins@cloudera.com>