IMPALA-7971 (follow-up). Fix compilation error
15a33d1ba was committed at about the same time as 5ced9160bd6, which
renamed one of the methods of the FileDescriptor class, causing a
compilation error. This follow-up mixes the semantic conflict.

Tested tests/custom_cluster/test_event_processing.py manually.

Change-Id: I8071b421f0dcbae2d303bd9f1e1f6f64657c49c0
Reviewed-on: http://gerrit.cloudera.org:8080/13184
Reviewed-by: Todd Lipcon <todd@apache.org>
Tested-by: Todd Lipcon <todd@apache.org>
(cherry picked from commit 095d609260ba8957c13e61c539892ab37c5da10b)

Change-Id: Iaee63a983a6c4cfcb885e75ee7cdac69de12d7bb
Reviewed-on: https://gerrit.sjc.cloudera.com/c/cdh/impala/+/45198
Reviewed-by: Jenkins User <jenkins@cloudera.com>
CDH-Build: Jenkins User <jenkins@cloudera.com>
Tested-by: Jenkins User <jenkins@cloudera.com>
CDH-Build: Joe McDonnell <joemcdonnell@cloudera.com>
Quasar-L0: Joe McDonnell <joemcdonnell@cloudera.com>
Tested-by: Joe McDonnell <joemcdonnell@cloudera.com>