Fix bug in report_benchmark_results.py
This was introduced by IMPALA-4618.

Exception was:
Traceback (most recent call last):
  File "tests/benchmark/report_benchmark_results.py", line 1135, in <module>
    report = Report(grouped, ref_grouped)
  File "tests/benchmark/report_benchmark_results.py", line 494, in __init__
    self.__analyze()
  File "tests/benchmark/report_benchmark_results.py", line 517, in __analyze
    query_variability_row = Report.QueryVariabilityRow(results, ref_results)
  File "tests/benchmark/report_benchmark_results.py", line 480, in __init__
    results, ref_results, for_variability = True)
  File "tests/benchmark/report_benchmark_results.py", line 1095, in build_exec_summary_str
    return str(comparison) + '\n'
  File "tests/benchmark/report_benchmark_results.py", line 844, in __str__
    return str(self.__build_table_variability())
  File "tests/benchmark/report_benchmark_results.py", line 891, in __build_table_variability
    output += str(self.combined_summary) + '\n'
  File "tests/benchmark/report_benchmark_results.py", line 713, in __str__
    table.add_row(table_row)
  File "/home/tarmstrong/Impala/incubator-impala/infra/python/env/local/lib/python2.7/site-packages/prettytable.py", line 818, in add_row
    raise Exception("Row has incorrect number of values, (actual) %d!=%d (expected)" %(len(row),len(self._field_names)))
Exception: Row has incorrect number of values, (actual) 8!=7 (expected)

Change-Id: I6a163e74fefc896464e35a6a1b91ce57de592f1a
Reviewed-on: http://gerrit.cloudera.org:8080/14925
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
(cherry picked from commit 4d9d6b49566cd99a06cf6bd4f1d202b7cfedead8)

Change-Id: I72e0d1a030c7c25afbbbb8023928efb53ce77520
Reviewed-on: https://gerrit.sjc.cloudera.com/c/cdh/impala/+/65299
Reviewed-by: Jenkins User <jenkins@cloudera.com>
CDH-Build: Jenkins User <jenkins@cloudera.com>
Quasar-L0: Jenkins User <jenkins@cloudera.com>
Tested-by: Jenkins User <jenkins@cloudera.com>