IMPALA-7917 (Part 3): Decouple Sentry from Impala
The third part of this patch introduces an interface called
AuthorizationManager to perform authorization management related
functions, such as granting/revoking a privilege, etc. Some existing
authorization management methods have been refactored to reduce the
need for if/else conditions to perform certain actions. This patch
moves code related to Sentry authorization management code to:
- SentryCatalogdAuthorizationManager
- SentryImpaladAuthorizationManager
The split makes it easier to differentiate between authorization DDL
operations performed in Catalogd vs Impalad.

This patch does not implement AuthorizationManager for Ranger.

This patch has no functionality change.

Testing:
- Ran all FE tests
- Ran all E2E authorization tests

Change-Id: I1a5d3e0a3e86ac2b0329b56247357fca93229dd0
Reviewed-on: http://gerrit.cloudera.org:8080/12684
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>