IMPALA-8578: part 1: reduce dependencies on *metrics.h
Before this patch there were 100s of compilation units that pulled in
metrics.h and the significant amount of code in that header. It was
painfully slow to recompile after changes to that file. The patch
reduces that significantly and mostly eliminates transitive inclusions
via other headers.

* Add metrics-fwds.h with forward declarations needed to have pointers
  to the various classes.
* Update headers to use metrics-fwds.h and move includes of *metrics.h
  to the .cc files.
* Add includes, etc to fix compilation errors where files depended
  on transitively-included headers from *metrics.h

This shaved about 30s off the build time on Jenkins - about a 4%
speedup.

I didn't end up removing anything from the headers - that is a bit
more work since most of the classes are templatized and need to
be explicitly instantiated in .cc files if functions are not
all defined in the headers.

Testing:
Ran a core build

Change-Id: Ie2942366cab5421f2db7c27e7da712ea6f775fdb
Reviewed-on: http://gerrit.cloudera.org:8080/13491
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Tim Armstrong <tarmstrong@cloudera.com>
(cherry picked from commit e78e6f0c260b342c67e055656d239438bca13288)

Change-Id: Ib2892921fd4a4da6416478ac00531f4da0632e76
Reviewed-on: https://gerrit.sjc.cloudera.com/c/cdh/impala/+/48102
Reviewed-by: Jenkins User <jenkins@cloudera.com>
CDH-Build: Jenkins User <jenkins@cloudera.com>
Tested-by: Jenkins User <jenkins@cloudera.com>
Quasar-L0: quasar-precommit User
Quasar-L0: Jenkins User <jenkins@cloudera.com>